title: Historie Albánie pro neználky i trapery
baseURL: https://modest-mayer-6ad947.netlify.com
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Po proudu času až do současnosti
  authors: Jan Dolák, Zdeněk Tajovský


